### ISSUE TITLE
Request: Fix typos in recipes

### ISSUE THREAD

**Issue by alfg** [alfg/opendrinks#766]
Some recipes may have typos and grammar errors in their description or instructions. Feel free to send a PR to add a correction.

**Comment by InternetRamen** [comment]
I would like to do this.

**Comment by alfg** [comment]
Thanks @InternetRamen!

I'll be leaving this as an open issue for any further corrections for anyone to fix as well.

**Comment by swai-collins** [comment]
Would also like to fix this

**Comment by aycer25** [comment]
Would it be possible for me to contribute to this issue as well?

**Comment by alfg** [comment]
@aycer25 If you find any errors to correct, feel free to submit a pull request.

**Comment by bibliofilo** [comment]
So I went through the list of **keywords** in https://opendrinks.io/keyword, and found a bunch that could be cleaned up. I might take them on category by category over the weekend (or if someone else wants to use these as inspiration for a pull request, go for it) but here they are for discussion first.

**Standardizing and adding special characters:**
_[stays the same <-- changed]_
alcoholic <-- alcohol 
curaçao -- curacao
kahlúa -- kahlua

**Spelling corrections:**
_[Correct -- Misspelling]_
baileys -- bailey's
bourbon -- burbon
carrot -- carot
cocoa powder -- cocoa-powder
hot drink -- hot-drink
iced tea -- ice tea -- ice-tea
liqueur -- liqeuer
watermelon -- matermelon
non-alcoholic -- non alcoholic -- not alcoholic
prosecco -- processcco
refreshing -- refresing
spices -- species

NOTE: These two aren't on this list because they have two or more correct spellings: Whiskey and whisky. Yogurt and yoghurt.

**Some were changed from plural to singular:**
The logic behind favoring singular is that there's consistently more common use in tags of singular vs. plural.
_[Singular -- Plural]_
berry -- berries
cherry -- cherries 
classic -- classics
fruit -- fruits
oreo -- oreo cookies
strawberry -- strawberries

**Location standardization:**
_[stays the same <-- changed]_
german -- germany
indian -- india
malasian -- malasia
mexican -- mexico

**Comment by kristina-hager** [comment]
@bibliofilo - cleaning up brute force sounds great!
has anyone given thought/looked into enforcing matters such as these with a json validator of some sort?
this would be enforcing a schema, but it also seems possible to set a list of allowed keywords, etc to avoid such misspelling issues.
Also, I have seen a few PRs have comments such as missing 'measure' field in the ingredients list. This can be automated to save the maintainers work.

**Comment by alfg** [comment]
@kristina-hager We added a validation script last year to check the schema of the recipe, but it can probably be improved on since it doesn't seem to catch everything. It runs as part of the tests. Good idea on common misspellings too.

https://github.com/alfg/opendrinks/tree/master/scripts

**Comment by bibliofilo** [comment]
@alfg @kristina-hager, I don't know how useful a suggestion it'd be, but a script that checked against existing Keywords and flagged new ones for review might be helpful. Or against common drink ingredients. I went through and did a second round of fixes a few days ago, here's the combined lists for any script that might need them. Here's the reasoning behind some of the non-misspelling fixes to maybe formalize a Keyword guideline in the documentation

Super boiled down, Keywords should be: Ingredients in the singular (apple rather than apples); and flavor, temperature, and country (etc) descriptors in the form of adjectives (spicy, hot, Brazilian rather than spice, hot drink, Brazil). 

The logic behind favoring singular over plural is that there was consistently more common use in tags of singular vs. plural. However, it may make sense to use plural for some fruits that are never used alone, like blueberries.

The idea behind using adjectives is that the keywords should describe the flavor or nature of the drink when they aren't outright ingredients. For example, people don't drink "alcohol" beverages or "carbonation" drinks, but "alcoholic beverages" and "carbonated drinks". The same goes for using countries and geographic regions as adjectives to be descriptors.

There's probably going to be a few exceptions, but the above really helped pare down anything that wasn't a misspelling to the least number of corrections.

**Adding special characters:**
_[stays the same <-- changed]_
curaçao -- curacao
kahlúa -- kahlua

**Spelling corrections:**
_[Correct -- Misspelling]_
alcoholic <-- alchoholic
baileys -- bailey's
bourbon -- burbon
carrot -- carot
champagne -- champage
cocktail -- cockatil
cocoa powder -- cocoa-powder
iced tea -- ice-tea
liqueur -- liqeuer
watermelon -- matermelon
non-alcoholic -- non alcoholic -- not alcoholic
prosecco -- processcco
refreshing -- refresing
spices -- species

NOTE: These two aren't on this list because they have two or more correct spellings: Whiskey and whisky. Yogurt and yoghurt. It may be worth running a script that standardizes them anyway, or fuses results of both.

**Some should be changed from plural to singular:**
_[Singular -- Plural]_
berry -- berries
cherry -- cherries 
classic -- classics
cocktail -- cocktails
fruit -- fruits -- mixed fruits
fruit juice -- fruits juice -- ruit juice
holiday -- holidays
oreo -- oreo cookies
strawberry -- strawberries

**Standardizing to adjectives:**
_(adjective -- noun or other)_
alcoholic -- alcohol
carbonated -- carbonation
easy -- easy to make
herbal -- herb
hot -- hot drink
iced tea -- ice tea

**Standardizing ingredient:**
_(final -- changed keyword)_
butter -- buttered
coconut -- coco

**Place name to adjective:**
_(final -- country name)_
german -- germany
indian -- india
malasian -- malasia
mexican -- mexico
singaporean -- singapore
